# Generated by Django 4.0.3 on 2022-04-26 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('creator_forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitnftmodel',
            name='username',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='username'),
        ),
    ]
