# Generated by Django 4.0.3 on 2022-04-27 00:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('creator_forms', '0003_alter_submitnftmodel_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitnftmodel',
            name='username',
            field=models.ForeignKey(default=uuid.uuid1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='username'),
        ),
    ]
