# Generated by Django 4.0.3 on 2022-04-27 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator_forms', '0009_alter_submitnftmodel_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitnftmodel',
            name='username',
            field=models.CharField(default=1, max_length=300, verbose_name='Username'),
            preserve_default=False,
        ),
    ]
